Fix problem with --recent option in repoquery
The problem was introduced by dnf privatization

AttributeError: 'Query' object has no attribute 'recent'

Closes: #736
Approved by: mhatina