Change the format_missing_requires callback, to look for packages of the same name with different versions and output their info.  This makes some implicit information explicit, to be clearer for the users. Eg. Before:
Error: Package: gnome-media-2.31.5-4.fc14.x86_64 (fedora)
           Requires: libgnome-control-center.so.1()(64bit)
           Available: 1:control-center-2.31.5-2.fc14.x86_64 (fedora)
               libgnome-control-center.so.1()(64bit)

...and after:

Error: Package: gnome-media-2.31.5-4.fc14.x86_64 (fedora)
           Requires: libgnome-control-center.so.1()(64bit)
           Available: 1:control-center-2.31.5-2.fc14.x86_64 (fedora)
               libgnome-control-center.so.1()(64bit)
           Removing: 1:control-center-2.30.1-2.fc13.x86_64 (@updates/13)
               Not found
           Updated By: 1:control-center-2.31.6-1.fc14.x86_64 (updates-testing)
               Not found

...this adds a few more lookups, but it's all in the error paths.