[repoquery] More strict queryformat parsing (RhBug:1631458)
Be more strict on parsing of queryformat and do not allow
strings like:

$ dnf repoquery --installed --queryformat '%{}'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/cli/commands/repoquery.py", line 296, in build_format_fn
    return rpm2py_format(opts.queryformat).format(po)
ValueError: Empty attribute in format string

$ dnf repoquery --installed --queryformat '{n}'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/cli/commands/repoquery.py", line 296, in build_format_fn
    return rpm2py_format(opts.queryformat).format(po)
KeyError: 'n'

$ dnf repoquery --installed --queryformat '%40-5{name}'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/cli/commands/repoquery.py", line 296, in build_format_fn
    return rpm2py_format(opts.queryformat).format(po)
ValueError: Invalid format specifier

Also all curly brackets which are not part of a valid format string
are now escaped.

https://bugzilla.redhat.com/show_bug.cgi?id=1631458