Fix traceback when upgrading unavailable environment
When environment of such id is not found (installed but not
available), comps_env variable is None and dnf fails with
AttributeError: 'NoneType' object has no attribute 'id'

= changelog =
msg: Fix traceback when upgrading unavailable environment
type: bugfix