sp err "environement" -> "environment"
Seems to cause:

AttributeError: 'GroupPersistor' object has no attribute 'environement'

when doing `dnf group mark install`