Reflect change of detecting user installed packages
Method _is_userinstalled is no longer part of Base class, was
removed by commit 1972a5fd27b27a03f18809699c21a83a92d35af5.

$ dnf repoquery --userinstalled
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 115, in cli_run
    cli.run()
  File "/usr/lib/python3.6/site-packages/dnf/cli/cli.py", line 1023, in run
    return self.command.run()
  File "/usr/lib/python3.6/site-packages/dnf/cli/commands/repoquery.py", line 531, in run
    if self.opts.list != 'userinstalled' or self.base._is_userinstalled(pkg):
AttributeError: 'BaseCli' object has no attribute '_is_userinstalled'