Remove call of dnf.rpmdetect_releasever
It fixes issue when releaser from host cannot be detect because rpmdb
cannot be open. If call will be redirected to an empty installroot it
cannot return string anyway.

======================================================================
ERROR: test_detect_releasever (tests.api.test_dnf_rpm.DnfRpmApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/rpm/__init__.py", line 39, in detect_releasever
    idx = ts.dbMatch('provides', distroverpkg)
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/rpm/transaction.py", line 59, in dbMatch
    mi = self.ts.dbMatch(*args, **kwds)
_rpm.error: rpmdb open failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/tests/api/test_dnf_rpm.py", line 16, in test_detect_releasever
    self.assertHasType(dnf.rpm.detect_releasever(installroot='/'), str)
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/rpm/__init__.py", line 41, in detect_releasever
    raise dnf.exceptions.Error('Error: %s' % str(e))
dnf.exceptions.Error: Error: rpmdb open failed