Fixed detecting whether deltarpm is installed
There is no requirement of deltarpm on CentOS/RHEL, but DNF was
still downloading .drpm. And then failed with traceback:

Delta RPMs reduced 50.9 MB of updates to 50.3 MB (1.1% saved)
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Traceback (most recent call last):
  File "/usr/bin/yum4", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 154, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 231, in do_transaction
    self.gpgsigcheck(install_pkgs)
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 257, in gpgsigcheck
    result, errmsg = self._sig_check_pkg(po)
  File "/usr/lib/python2.7/site-packages/dnf/base.py", line 1263, in _sig_check_pkg
    sigresult = dnf.rpm.miscutils.checkSig(ts, po.localPkg())
  File "/usr/lib/python2.7/site-packages/dnf/rpm/miscutils.py", line 34, in checkSig
    fdno = os.open(package, os.O_RDONLY)
OSError: [Errno 2] No such file or directory: '/var/cache/dnf/updates-c9865004c76e8c77/packages/bind-libs-lite-9.9.4-51.el7_4.2.x86_64.rpm'