Fix python2 doesn't have e.__traceback__ attribute
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dnf/yum/rpmtrans.py", line 455, in callback
    exept_list = traceback.format_exception(type(e), e, e.__traceback__)
AttributeError: 'exceptions.TypeError' object has no attribute '__traceback__'
FATAL ERROR: python callback <bound method RPMTransaction.callback of <dnf.yum.rpmtrans.RPMTransaction object at 0x7efc2e983bd0>> failed, aborting!