Fix: id argument of libdnf.repo.Repo() constructor can't be None
Id with the None value causes a traceback.
ValueError: invalid null reference in method 'new_Repo',
argument 1 of type 'std::string const &'