Fix behavior of `install-n` command
Commit de9643afbdf5bb (first shipped in dnf 4.2.8) changed opts.command
from a list to a simple string, but code in InstallCommand still handled
it as if it was a list.

This broke silently because Python will iterate over a string character
by character, so it never produced a syntax error or an exception that
would be noticed.

But it broke behavior of the `install-n` form, since it would no longer
detect that command to restrict search of packages.

Before this commit, this command would (incorrectly) succeed:
  $ dnf install-n joe-4.6

After this commit:
  $ dnf install-n joe-4.6
  No match for argument: joe-4.6
    * Maybe you meant: joe
  Error: Unable to find a match: joe-4.6

Closes: #1611
Approved by: m-blaha