Print nicer DnssecErrors (RhBug:1813244)
Print errors more readable by users. Instead of current exception-like
error:

$ dnf list dnf
DNSSEC extension: Testing already imported keys for their validity.
Email address should contain exactly one '@' sign.
Exception raised in DNSSEC extension: email=@dnsoarc#drool@copr.fedorahosted.org, exception=<DnssecError, value='Email address should contain exactly one '@' sign.'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf/dnssec.py", line 287, in check_imported_keys_validity
    result = DNSSECKeyVerification.verify(key)
  File "/usr/lib/python3.7/site-packages/dnf/dnssec.py", line 227, in verify
    result = DNSSECKeyVerification._cache_miss(input_key)
  File "/usr/lib/python3.7/site-packages/dnf/dnssec.py", line 186, in _cache_miss
    status, result = ctx.resolve(email2location(input_key.email),
  File "/usr/lib/python3.7/site-packages/dnf/dnssec.py", line 63, in email2location
    raise DnssecError(msg)
dnf.dnssec.DnssecError: Email address should contain exactly one '@' sign.
Email address should contain exactly one '@' sign.

Print shorter and clearer error message:

$ dnf list dnf
DNSSEC extension: Testing already imported keys for their validity.
DNSSEC extension error (email=@dnsoarc#drool@copr.fedorahosted.org): Email address must contain exactly one '@' sign.

https://bugzilla.redhat.com/show_bug.cgi?id=1813244