Set /tmp installroot for test that requires to access rpmdb
It resolves issues when tests access data outside of buildroot.

======================================================================
ERROR: test_detect_releasever (tests.api.test_dnf_rpm.DnfRpmApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/rpm/__init__.py", line 39, in detect_releasever
    idx = ts.dbMatch('provides', distroverpkg)
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/rpm/transaction.py", line 59, in dbMatch
    mi = self.ts.dbMatch(*args, **kwds)
_rpm.error: rpmdb open failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/tests/api/test_dnf_rpm.py", line 16, in test_detect_releasever
    self.assertHasType(dnf.rpm.detect_releasever(installroot='/'), str)
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/rpm/__init__.py", line 41, in detect_releasever
    raise dnf.exceptions.Error('Error: %s' % str(e))
dnf.exceptions.Error: Error: rpmdb open failed

======================================================================
ERROR: Test Cli.configure as user.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/mock.py", line 1256, in patched
    return func(*args, **keywargs)
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/tests/test_cli.py", line 193, in test_configure_user
    self.cli.configure(['update', '-c', self.conffile])
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/cli/cli.py", line 979, in configure
    self.command.configure()
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/cli/commands/upgrade.py", line 59, in configure
    commands._checkGPGKey(self.base, self.cli)
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/cli/commands/__init__.py", line 67, in _checkGPGKey
    if not base._gpg_key_check():
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/base.py", line 1740, in _gpg_key_check
    idx = myts.dbMatch('name', 'gpg-pubkey')
  File "/builddir/build/BUILD/dnf-git-9263.3ee08c3/dnf/rpm/transaction.py", line 59, in dbMatch
    mi = self.ts.dbMatch(*args, **kwds)
_rpm.error: rpmdb open failed