Raise error for group_install() if unknown group_id
It fixes traceback if group_id doesn't exist. It is only important for API
users.

File "/usr/lib/python3.5/site-packages/dnf/comps.py", line 540, in _group_install
  p_grp.name = group.name
AttributeError: 'NoneType' object has no attribute 'name'