[repoquery] Handle --querytags, before updateFailSafeData
Otherwise the error occures instead of listing available tags:
$ dnf repoquery --querytags
Error: Sack was not initialized