package: fix debugsource_name/source_debug_name on a source package
Source packages have source_name = None, so it would throw:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Closes: #1469
Approved by: j-mracek